// Generated by MambaScript
var present = console.log;
// Generated by MambaScript
var MambaScript, PLUGIN_NAME, PluginError, replaceExtension, through;
through = require('through2');
cache$ = require('gulp-util');
PluginError = cache$.PluginError;
replaceExtension = cache$.replaceExtension;
MambaScript = require('mambascript');
PLUGIN_NAME = 'gulp-mamba';
module.exports = function (opts) {
  return through.obj(function (file, enc, callback) {
    var msAst, input, js, jsAst;
    if (file.isNull())
      return callback();
    if (file.isStream())
      throw new PluginError(PLUGIN_NAME, 'Not supports Stream');
    if (!file.isBuffer())
      throw new PluginError(PLUGIN_NAME, 'Supports Buffer only');
    input = file.contents.toString('utf8');
    msAst = MambaScript.parse(input, opts.msAst);
    jsAst = MambaScript.compile(msAst, opts.jsAst);
    js = MambaScript.js(jsAst, opts.js);
    file.contents = Buffer.from(js, 'utf8');
    file.path = replaceExtension(file.path, '.js');
    this.push(file);
    return callback();
  });
};
